name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  cmake:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        container: [
            "mariojim/touchegg-music-client-deps:debian",
            "mariojim/touchegg-music-client-deps:archlinux"
        ]

    container:
      image: ${{ matrix.container }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run CMake
        run: |
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Debug
          make -C build
