name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        container: [
            "mariojim/touchegg-music-client-deps:debian",
            "mariojim/touchegg-music-client-deps:archlinux"
        ]

    container:
      image: ${{ matrix.container }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run CMake
        run: |
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Debug
          make -C build

  formatter:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -yq clang-format

      - name: Run clang-format
        run: clang-format --Werror --dry-run --style=file src/**/*.h src/**/*.cpp
